### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [vitaliigrybov/prj-rev-bwfs-tea-cozy#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project! The page looks great and you've done an excellent job keeping both the project folder and the code itself neat, organized, and readable throughout. Nice use of flex display to help align items throughout the page as well!

Behind the scenes, consider using a general class to help reduce the number of times flex styling is repeated throughout the css. Also, consider replacing the span element for a smaller heading to avoid adjusting the span to behave like a block display element. 

Great use of the header, nav, and footer semantic tags. As a next step, check out [this info](https://www.w3schools.com/html/html5_semantic_elements.asp) to see some other examples of tags you could use in future projects.	

Have fun and keep up the good work!

**Comment by vitaliigrybov** [comment]
Thank you for your review and your advices!
